### ISSUE TITLE
what dataset you used

### ISSUE THREAD

**Issue by Linranran** [nmeripo/Identifying-Clothing-Attributes#1]
hi  nmeripo:
       i am interesting in attributes recognition recently.could you tell me what dataset you used in your codes ?

**Comment by nmeripo** [comment]
Hey Linranran, please look into the updated README for the download link of Clothing Attributes Dataset.

**Comment by nmeripo** [comment]
Hey Linranran, please look into the updated README for the download link of Clothing Attributes Dataset.

**Comment by Linranran** [comment]
@nmeripo  thank you for your reply ,have a good day
