### ISSUE TITLE
how to predict multiple attributes simultaneously

### ISSUE THREAD

**Issue by Linranran** [nmeripo/Identifying-Clothing-Attributes#2]
dear  nmeripo：
        I think  the network you uesed treat the attributes recognition as a classification problem.and only can predict one sub-attribute of the category. i have read some papers about attribute recognize,and those  papers usually add K  paralleling fc layers(k is the number of the attributes,fc0 prEdict the attribute0,fc1 predict the attribute1...fck predict the attributeK) . so i think you can make a little revise about the network and the data preprocess file. and i will have a try to do this 
best
ranran

**Comment by nmeripo** [comment]
You can use sibling fc layers but that leads to overfitting in this case. Use conv layers to effectively reduce the feature map size to perform multi-task predictions.
